name: Issue Manager

on:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.4.0
        with:
          token: ${{ secrets.ISSUE_DB }}
          config: >
            {
                "cli": {
                    "delay": 0,
                    "message": "",
                    "remove_label_on_comment": false,
                    "remove_label_on_close": false
                }
            }
